apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-ygla
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-ygla
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-ygla
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-ygla
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-ygla
    spec:
      containers:
      - image: quay.io/bootstrap/rhtap-demo-vnsf-tenant/rhtap-demo-app/hacbs-test-project-ygla@sha256:4b5f9d886756a486c6caa3e8f35a1f32a8e2f51a3d2e1f8c124d424d2d87d0c7
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
